import { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { FileCheck } from 'lucide-react';

interface CreateJobDialogProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export function CreateJobDialog({ open, onClose, onSuccess }: CreateJobDialogProps) {
  const { profile } = useAuth();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    quote_number: '',
    client_name: '',
    address: '',
    description: '',
    notes: '',
    projected_start_date: '',
    projected_end_date: '',
  });
  const [autoGenerateQuoteNumber, setAutoGenerateQuoteNumber] = useState(true);

  // Auto-generate quote number when dialog opens
  async function generateQuoteNumber() {
    try {
      const { data, error } = await supabase.rpc('generate_quote_number');
      if (error) throw error;
      setFormData(prev => ({ ...prev, quote_number: data }));
    } catch (error: any) {
      console.error('Error generating quote number:', error);
      toast.error('Failed to generate quote number');
    }
  }

  // Generate quote number when dialog opens
  useEffect(() => {
    if (open && autoGenerateQuoteNumber && !formData.quote_number) {
      generateQuoteNumber();
    }
  }, [open]);

  async function handleSubmit(e: React.FormEvent) {
    // CRITICAL: Prevent default FIRST to block page reload
    e.preventDefault();
    e.stopPropagation();
    
    // Office role validation
    if (profile?.role !== 'office') {
      toast.error('Only office staff can create quotes');
      return;
    }

    // Manual scroll anchor - record EXACT scroll position at the very start
    const savedScrollPosition = window.scrollY;
    console.log('💾 Saved scroll position:', savedScrollPosition);

    setLoading(true);

    try {
      // Quote number will be auto-generated by database trigger if not provided
      // Job number will be assigned later when status changes to 'active' or 'prepping'
      
      // Insert job with only valid columns
      // All new jobs start in 'quoting' status with quote_number (no job_number yet)
      const { data: job, error } = await supabase
        .from('jobs')
        .insert({
          name: formData.name.trim(),
          quote_number: formData.quote_number.trim() || null, // Will be auto-generated if null
          client_name: formData.client_name.trim(),
          address: formData.address.trim(),
          description: formData.description.trim() || null,
          notes: formData.notes.trim() || null,
          documents: [], // Empty array for custom folders
          components: [], // Empty array for job components
          status: 'quoting', // All new jobs start in quoting phase
          projected_start_date: formData.projected_start_date || null,
          projected_end_date: formData.projected_end_date || null,
          created_by: profile.id,
        })
        .select()
        .single();

      if (error) {
        console.error('Quote creation error:', error);
        throw new Error(error.message || 'Failed to create quote');
      }

      // Restore scroll position AFTER updates but BEFORE toast
      requestAnimationFrame(() => {
        window.scrollTo({ top: savedScrollPosition, behavior: 'instant' });
        console.log('📍 Scroll restored to:', savedScrollPosition);
      });

      toast.success(`Quote "${job.quote_number}" created successfully`, {
        duration: 2000,
        position: 'bottom-right'
      });
      
      // Reset form
      setFormData({
        name: '',
        quote_number: '',
        client_name: '',
        address: '',
        description: '',
        notes: '',
        projected_start_date: '',
        projected_end_date: '',
      });
      
      // Close dialog and refresh (scroll position already restored above)
      onSuccess();
    } catch (error: any) {
      console.error('Quote creation failed:', error);
      toast.error(error.message || 'Failed to create quote');
    } finally {
      setLoading(false);
    }
  }

  function handleClose() {
    if (!loading) {
      onClose();
      // Reset form on close
      setFormData({
        name: '',
        quote_number: '',
        client_name: '',
        address: '',
        description: '',
        notes: '',
        projected_start_date: '',
        projected_end_date: '',
      });
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileCheck className="w-5 h-5 text-blue-600" />
            Create New Quote
          </DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4">
            <div className="flex items-center gap-2 mb-2">
              <FileCheck className="w-4 h-4 text-blue-600" />
              <p className="font-semibold text-blue-900">Numbering System</p>
            </div>
            <div className="text-sm text-blue-800 space-y-1">
              <p><strong>Quote Number:</strong> YYXXX format (e.g., 26001 for 2026, quote #1)</p>
              <p><strong>Proposal Number:</strong> Assigned when materials/financials are added for contract versions</p>
              <p><strong>Job Number:</strong> Auto-assigned when moved to Active/Prepping after contract signing</p>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="name">Job Name *</Label>
            <Input
              id="name"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              placeholder="e.g., Smith Barn Construction"
              required
              disabled={loading}
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="quote_number">Quote Number</Label>
              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  id="auto-generate"
                  checked={autoGenerateQuoteNumber}
                  onChange={(e) => {
                    setAutoGenerateQuoteNumber(e.target.checked);
                    if (e.target.checked && !formData.quote_number) {
                      generateQuoteNumber();
                    }
                  }}
                  className="rounded"
                />
                <label htmlFor="auto-generate" className="text-xs text-muted-foreground">
                  Auto-generate
                </label>
              </div>
            </div>
            <Input
              id="quote_number"
              value={formData.quote_number}
              onChange={(e) => setFormData({ ...formData, quote_number: e.target.value })}
              placeholder="26001"
              disabled={loading || autoGenerateQuoteNumber}
              className={autoGenerateQuoteNumber ? 'bg-muted' : ''}
            />
            {autoGenerateQuoteNumber && (
              <p className="text-xs text-muted-foreground">
                ✓ Quote number will be auto-generated
              </p>
            )}
            <p className="text-xs text-muted-foreground mt-1">
              💡 Proposal & Job numbers assigned automatically later
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="client_name">Client Name</Label>
              <Input
                id="client_name"
                value={formData.client_name}
                onChange={(e) => setFormData({ ...formData, client_name: e.target.value })}
                placeholder="John Smith"
                disabled={loading}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="address">Job Address *</Label>
              <Input
                id="address"
                value={formData.address}
                onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                placeholder="123 Main St, City, State"
                required
                disabled={loading}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="start-date">Projected Start Date</Label>
              <Input
                id="start-date"
                type="date"
                value={formData.projected_start_date}
                onChange={(e) => setFormData({ ...formData, projected_start_date: e.target.value })}
                disabled={loading}
              />
              <p className="text-xs text-muted-foreground">
                Job appears in field view on this date
              </p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="end-date">Projected End Date</Label>
              <Input
                id="end-date"
                type="date"
                value={formData.projected_end_date}
                onChange={(e) => setFormData({ ...formData, projected_end_date: e.target.value })}
                disabled={loading}
                min={formData.projected_start_date || undefined}
              />
              <p className="text-xs text-muted-foreground">
                Estimated completion date
              </p>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              rows={3}
              placeholder="Project details, scope, etc."
              disabled={loading}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="notes">Notes</Label>
            <Textarea
              id="notes"
              value={formData.notes}
              onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
              rows={3}
              placeholder="Internal notes, special instructions, etc."
              disabled={loading}
            />
          </div>

          <div className="bg-muted p-4 rounded-lg text-sm text-muted-foreground">
            <p className="font-medium mb-2">📁 Document Management</p>
            <p>After creating the quote, you can add custom document folders (Drawings, Specs, POs, etc.) and upload files to organize job documents.</p>
          </div>

          <div className="flex gap-2 justify-end pt-4 border-t">
            <Button type="button" variant="outline" onClick={handleClose} disabled={loading}>
              Cancel
            </Button>
            <Button type="submit" disabled={loading} className="bg-blue-600 hover:bg-blue-700">
              {loading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2" />
                  Creating...
                </>
              ) : (
                <>
                  <FileCheck className="w-4 h-4 mr-2" />
                  Create Quote
                </>
              )}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
